### ISSUE TITLE
security issues due to INI version

### ISSUE THREAD

**Issue by okobsamoht** [maghoff/prog#1]
Hi
i used yout package 'program' in one of my npm package that i use to genereate some react component.
github bot is alerting about security due to the version of the ini package you used.

i can helpe upgrade the program package or is there a update / upgrade planned soon?

see in the screen shot below
_________________________________________

![Screenshot from 2022-02-17 14-57-05](https://user-images.githubusercontent.com/5099481/154496520-025443d7-1bad-4351-a5a9-5845c4fef1e2.png)
_________________________________________

regards.

**Comment by maghoff** [comment]
No upgrade will happen, your best course of action is to fork.

I wouldn't think this package would be useful as a dependency (but rather only installed as a program to run locally). Are you sure your are indeed looking at the right dependency?
